theme = "solarized_dark"


[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# Mimic Vim's 'V' (Visual Line Mode)
V = ["select_mode", "extend_to_line_bounds"]

# Vim uses 'D' to delete until end of line
D = ["extend_to_line_end", "delete_selection", ]

# Vim uses 'G' to go to the very bottom, Helix uses 'ge' (goto end)
G = "goto_file_end"

# Vim uses '%' for matching pairs, Helix uses 'm' (match mode)
# This maps % to quickly match the enclosing character 
"%" = "match_brackets"

# Add lazygit integration to helix
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# line-up
C-e = ["keep_primary_selection","extend_line","yank","move_line_up","open_above","normal_mode","replace_with_yanked", "move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# line-down
C-d = ["keep_primary_selection","extend_line","delete_selection", "paste_after", "move_line_down"]


# `jk` to enter normal mode
[keys.insert]
j = { k = "normal_mode" }

